name: 'Build and Test QCAForge App'

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
      - dev
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        #   - platform: "macos-latest" # for Arm based macs (M1 and above).
        #     args: "--target aarch64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          #Removed windows-latest from the matrix as it has a very long build time.
          # - platform: "windows-latest"
          #   args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin' || '' }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install NPM dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build Backend
        run: |
          cargo build --release ${{ matrix.args }}