name: 'build-test'

on:
  push:
    branches:
      - '*'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./src-tauri

      - name: Install NPM dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Build Tauri
        run: npm run tauri build